name: Concurrent Log Handler (CLH) tests

on:
  push:
    branches:
      - master  # or the name of your primary branch
  pull_request:
    branches:
      - master  # or the name of your primary branch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Note that the new tests don't work on Python 2.7
        # python-version: [2.7, 3.x]
        python-version: [3.6, 3.x]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]

    - name: Run tests
      run: |
        tox
